"""
Django settings for sassy_baka project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import environ

from core.prompts import TENDER_ASSESSMENT_PROMPT as DEFAULT_TENDER_ASSESSMENT_PROMPT

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ``backend/.env`` is local-only (and gitignored). It lets development and
# deployment environments provide secrets without adding them to source code.
env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-lc7@$w6cwchwcnlq98llm(=*(0!mh(6-x=4=2tw%rul(jl1qt4"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "fourloop-backend.robinrangi.com",
    "localhost",
    "127.0.0.1",
]

CSRF_TRUSTED_ORIGINS = [
    "https://fourloop-backend.robinrangi.com",
    "http://fourloop.robinrangi.com",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOWED_ORIGINS = [
    "https://fourloop-backend.robinrangi.com",
    "http://fourloop.robinrangi.com",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
CORS_ALLOW_CREDENTIALS = True

# Testing only: authenticated REST API requests may use the session cookie
# without an X-CSRFToken header. Do not use this setting in production.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "core.authentication.CsrfExemptSessionAuthentication",
    ),
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "core.apps.CoreConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "sassy_baka.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sassy_baka.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# The tender crawler intentionally has its own SQLite database.  It contains
# canonical active tenders plus crawler lifecycle state; do not point this at
# Django's authentication database.
TENDER_DATABASE_PATH = env.str(
    "TENDER_DATABASE_PATH", default=str(BASE_DIR / "scraping" / "uk_open_tenders.db")
)

# Put the company's description and capabilities in this Markdown file (or set
# TENDER_COMPANY_CONTEXT_PATH to the existing private file in the deployment).
TENDER_COMPANY_CONTEXT_PATH = env.str(
    "TENDER_COMPANY_CONTEXT_PATH",
    default=str(BASE_DIR / "company_description_and_capabilities.md"),
)

OPENAI_API_KEY = env.str("OPENAI_API_KEY", default="")
OPENAI_TENDER_MODEL = env.str("OPENAI_TENDER_MODEL", default="gpt-4o-mini")
TENDER_ASSESSMENT_FAKE_MODE = env.bool("TENDER_ASSESSMENT_FAKE_MODE", default=False)
TENDER_ASSESSMENT_PROMPT_VERSION = env.str(
    "TENDER_ASSESSMENT_PROMPT_VERSION", default="2026-09-26"
)
TENDER_ASSESSMENT_PROMPT = env.str(
    "TENDER_ASSESSMENT_PROMPT", default=DEFAULT_TENDER_ASSESSMENT_PROMPT
)


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}
