# Generated by Django 6.1.1 on 2026-09-26 02:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_information', models.TextField(blank=True, help_text='Raw input from the user about their business.')),
                ('markdown_context', models.TextField(blank=True, help_text='AI-generated markdown format of company capabilities.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companyprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenderAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocid', models.CharField(max_length=512)),
                ('risk_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('risks', models.TextField()),
                ('fit_reasoning', models.TextField()),
                ('recommendation_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('assessment_json', models.JSONField()),
                ('model_name', models.CharField(max_length=128)),
                ('prompt_version', models.CharField(max_length=128)),
                ('company_context_sha256', models.CharField(max_length=64)),
                ('tender_updated_at', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tender_assessments',
                'ordering': ['-assessed_at'],
                'unique_together': {('user', 'ocid')},
            },
        ),
    ]
