# Generated by Django 6.1.1 on 2026-09-26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TenderAssessment",
            fields=[
                ("ocid", models.CharField(max_length=512, primary_key=True, serialize=False)),
                (
                    "risk_rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("risks", models.TextField()),
                ("fit_reasoning", models.TextField()),
                (
                    "recommendation_rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("assessment_json", models.JSONField()),
                ("model_name", models.CharField(max_length=128)),
                ("prompt_version", models.CharField(max_length=128)),
                ("company_context_sha256", models.CharField(max_length=64)),
                ("tender_updated_at", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assessed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tender_assessments",
                "ordering": ["-assessed_at"],
            },
        ),
    ]
